DROP TABLE IS EXISTS contact;
DROP TABLE IF EXISTS entries;

CREATE TABLE contact (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sender TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    body TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE entries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    created TIMESTAMP NOT NULL,
    code TEXT NOT NULL,
    extension TEXT NOT NULL
);